project:
  type: website
  output-dir: docs
  execute-dir: project
  resources: 
    - "www/"
    - "CNAME"

website:
  title: "x-share"
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: Home
        icon: house
  page-footer: 
    right: "Powered by Quarto. Built on Raspberry Pi."
    left: "Â© 2025, Patrick Altmeyer"

format:
  html:
    theme:
      - theme-light.scss
      - brand
    css: styles.css
    toc: true
